"""empty message

Revision ID: 2d59357c477e
Revises: 2e6b4fde3a3f
Create Date: 2017-12-17 22:28:18.155517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d59357c477e'
down_revision = '2e6b4fde3a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=True),
    sa.Column('datecreated', sa.DateTime(), nullable=True),
    sa.Column('datemodified', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_recipe_category_category_name'), 'recipe_category', ['category_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_category_category_name'), table_name='recipe_category')
    op.drop_table('recipe_category')
    # ### end Alembic commands ###
