"""empty message

Revision ID: 3ce59fc8948f
Revises: 3686a5b98e09
Create Date: 2018-01-06 14:33:47.495303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce59fc8948f'
down_revision = '3686a5b98e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('datecreated', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('blacklist', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_index(op.f('ix_blacklist_blacklist'), 'blacklist', ['blacklist'], unique=True)
    op.create_index(op.f('ix_blacklist_userid'), 'blacklist', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklist_userid'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_blacklist'), table_name='blacklist')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
