"""empty message

Revision ID: 448630545219
Revises: 1aa9fed36cc3
Create Date: 2017-12-19 09:27:16.189076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448630545219'
down_revision = '1aa9fed36cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('datecreated', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('datemodified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'datemodified')
    op.drop_column('recipes', 'datecreated')
    # ### end Alembic commands ###
