"""empty message

Revision ID: 5066df4ae2cc
Revises: 448630545219
Create Date: 2017-12-19 12:31:54.274268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5066df4ae2cc'
down_revision = '448630545219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipe_name', sa.String(length=250), nullable=False))
    op.create_index(op.f('ix_recipes_recipe_name'), 'recipes', ['recipe_name'], unique=False)
    op.drop_index('ix_recipes_name', table_name='recipes')
    op.drop_column('recipes', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.create_index('ix_recipes_name', 'recipes', ['name'], unique=False)
    op.drop_index(op.f('ix_recipes_recipe_name'), table_name='recipes')
    op.drop_column('recipes', 'recipe_name')
    # ### end Alembic commands ###
